-- Ejecuta este script en el SQL Editor de Supabase

-- Crear tabla de respuestas
CREATE TABLE respuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datos JSONB NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configurar permisos para que el backend pueda acceder
ALTER TABLE respuestas ENABLE ROW LEVEL SECURITY;

-- Permitir todas las operaciones asumiendo que el backend maneja la autenticación
CREATE POLICY "Permitir todo al backend"
ON respuestas
FOR ALL
USING (true)
WITH CHECK (true);
